apiVersion: v1
kind: Pod
metadata:
  name: faraz-demo-pod
  namespace: validation-admission-controller-demo
spec:
  containers:
  - name: demo
    image: ubuntu
    command: ["/bin/sh"]
    args: ["-c", "while true; do echo hello; sleep 10;done"]
    resources:
      requests:
        memory: "3Gi"
        cpu: "500m"
      limits:
        memory: "3Gi"
        cpu: "500m"
