apiVersion: apps/v1
kind: Deployment
metadata:
  name: faraz-guestbook-deploy
spec:
  replicas: 3
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: faraz-guestbook-ui
  template:
    metadata:
      labels:
        app: faraz-guestbook-ui
    spec:
      containers:
      - image: quay.io/argoprojlabs/argocd-e2e-container:0.2
        name: guestbook-ui
        ports:
        - containerPort: 80