apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: faraz-web
spec:
  selector:
    matchLabels:
      app: faraz-nginx
  serviceName: "nginx"
  replicas: 3
  minReadySeconds: 10
  template:
    metadata:
      labels:
        app: faraz-nginx
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80
          name: web
        volumeMounts:
        - name: www-standard
          mountPath: /usr/share/nginx/html
  volumeClaimTemplates:
  - metadata:
      name: www-standard
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: standard
      resources:
        requests:
          storage: 1Gi
