apiVersion: apps/v1
kind: Deployment
metadata:
  name: faraz-nginx-deployment-node-affinity-required
  labels:
    app: faraz-nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: faraz-nginx
  template:
    metadata:
      labels:
        app: faraz-nginx
    spec:
      affinity:
       nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
         nodeSelectorTerms:
         - matchExpressions:
           - key: type
             operator: In
             values:
             - faraz-node-affinity-required-demo
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80

