apiVersion: apps/v1
kind: Deployment
metadata:
  name: faraz-nginx-deployment
  labels:
    app: faraz-nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: faraz-nginx
  template:
    metadata:
      labels:
        app: faraz-nginx
    spec:
      nodeSelector:
        node-name: faraz-worker
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80
