apiVersion: apps/v1
kind: Deployment
metadata:
  name: faraz-nginx-deployment-taint-toleration-demo
  labels:
    app: faraz-nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: faraz-nginx
  template:
    metadata:
      labels:
        app: faraz-nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80
      tolerations:
      - key: "fz-tolerant-key"
        operator: "Equal"
        value: "fz-tolerant-value"
        effect: "NoSchedule"
