apiVersion: apps/v1
kind: Deployment
metadata:
  name: faraz-django-app
  labels:
    app: faraz-django-app-label
spec:
  replicas: 2
  selector:
    matchLabels:
      app: faraz-django-app-label
  template:
    metadata:
      labels:
        app: faraz-django-app-label
    spec:
      containers:
      - name: faraz-django-app-container-k8s
        image: fzhussain/django-simple-resume-app-testing-k8s:v1
        volumeMounts:
        - name: faraz-db-connection
          mountPath: /fz/configmap
        - name: faraz-db-password
          mountPath: /fz/secret
        ports:
        - containerPort: 8000
      volumes:
      - name: faraz-db-connection
        configMap:
          name: faraz-test-cm
      - name: faraz-db-password
        secret:
          secretName: faraz-test-secret-db-password

