apiVersion: apps/v1
kind: Deployment
metadata:
  name: faraz-django-app
  labels:
    app: faraz-django-app-label
spec:
  replicas: 2
  selector:
    matchLabels:
      app: faraz-django-app-label
  template:
    metadata:
      labels:
        app: faraz-django-app-label
    spec:
      containers:
      - name: faraz-django-app-container-k8s
        image: fzhussain/django-simple-resume-app-testing-k8s:v1
        env:
          - name: DB-PORT
            valueFrom:
              configMapKeyRef:
                name: faraz-test-cm
                key: db-port
          - name: DB-PASSWORD
            valueFrom:
              secretKeyRef:
                name: faraz-test-secret-db-password
                key: db-password
        ports:
        - containerPort: 8000
